# Generated by Django 3.1.5 on 2021-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tech_stack', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('preview', models.ImageField(upload_to='previews')),
                ('live_link', models.CharField(blank=True, max_length=500)),
                ('github_link', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
